 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.7.1
     steps:
       - setup_remote_docker
       - checkout
       - run: sudo pip install -U -r requirements.txt
       - run: export PYTHONPATH="~/project/iv/"
       - run: python3 src/api.py
       - run: make test
