 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.7.1
     steps:
       - checkout
       - run: sudo pip install -U -r requirements.txt
       - run: export PYTHONPATH=`pwd`
       - run: pytest tests/
