 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.7.1
     steps:
       - setup_remote_docker
       - checkout
       - run: docker build -t python-pyramid docker/pyramid
       - run: sudo pip install -U -r requirements.txt
       - run: export PYTHONPATH=`pwd`
       - run: make test
