 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.7.1
         environment:
           PYTHONPATH=/home/circleci/project
     steps:
       - setup_remote_docker
       - checkout
       - run: sudo pip install -U -r requirements.txt
       - run: python3 src/api.py &
       - run: sleep 5
       - run: ps -ax
       - run: make test
