 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.7.1
     steps:
       - checkout
       - run: pip install --user --upgrade pip
       - run: pip install --user -r requirements.txt
       - run: pytest tests/
