version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - working_directory: ~/iv
        # environment:
        #   PIPENV_VENV_IN_PROJECT: true

    steps:
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - tests:
          name: Run tests
          command: pytest ~/iv/tests
